name: Snapshot & File Index
on:
  push:
    branches: [ "main" ]
jobs:
  snapshot:
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: main
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Generate FILELIST.md
        run: node scripts/make-filelist.mjs
      - name: Commit FILELIST.md back
        run: |
          if ! git diff --quiet FILELIST.md; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add FILELIST.md
            git commit -m "chore: update FILELIST.md [skip ci]"
            git push
          else
            echo "No changes to FILELIST.md"
          fi
